# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95aa1c7c631ada807c719adcd31c0df2463efce2b7fc6f5c30cddc2142a384ce43fd7142ee59f3bf93b4c534a24f1d8250af60e9bab5a35d87469e3ad25cb7c8

test:
  secret_key_base: 74eee59536e720ade03c4af967bd97d0aae2d4c748707f21c74bee5be25df245874e327913a11cbae692e6e9b1b1d2b14e400c6c5675d7fadcbf7a666886ff29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
